os: Visual Studio 2017
version: 1.1.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- dotnet --info
- dotnet restore
build_script:
- dotnet build -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
- dotnet test .\CrockfordBase32Encoder.Tests\CrockfordBaseEncoder.Tests.csproj